language: python
python:
    - "2.7"
    - "3.6"
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - build-essential
            - gfortran
env:
    - MPLBACKEND="agg"
install:
    - pip uninstall numpy -y
    - pip install coveralls pytest-cov
    - pip install dcor
    - pip install -r requirements.txt
    - FC=gfortran python setup.py develop
script: pytest --cov=starvine
after_success: coveralls
